import { AppShell } from "@/components/app-shell";

const sections = [
  {
    title: "Architecture",
    body:
      "Next.js app router handles role-based pages. PostgreSQL stores hierarchy and collaboration data. Department entries are the only write source, and aggregation services generate scope summaries upward."
  },
  {
    title: "Navigation",
    body:
      "Login, dashboard, collaborations list, new collaboration, collaboration detail, analytics, and profile are the only required screens. Navigation stays flat and role-aware."
  },
  {
    title: "Aggregation logic",
    body:
      "Every collaboration record is stamped with university, campus, institute, department, and industry keys. KPIs and charts are generated by grouping these rows according to the signed-in user's allowed scope."
  },
  {
    title: "Roadmap",
    body:
      "Set up auth and RBAC, create schema, connect CRUD forms, expose analytics APIs, then polish dashboard filters and export options. The detailed project brief also lives in README.md."
  }
];

export default function DocsPage() {
  return (
    <AppShell role="admin" title="Docs">
      <section className="panel p-6">
        <p className="eyebrow">Implementation guide</p>
        <h2 className="mt-2 text-3xl font-semibold">Application blueprint</h2>
      </section>
      <section className="grid gap-4 md:grid-cols-2">
        {sections.map((section) => (
          <article key={section.title} className="panel p-5">
            <p className="eyebrow">{section.title}</p>
            <p className="mt-3 text-base leading-7 text-slate-600">{section.body}</p>
          </article>
        ))}
      </section>
    </AppShell>
  );
}
