import { CollaborationRecord } from "@/lib/types";

export const collaborations: CollaborationRecord[] = [
  {
    id: "collab-001",
    universityId: "uni-1",
    universityName: "MIT University",
    campusId: "campus-blr",
    campusName: "Bengaluru Campus",
    instituteId: "inst-eng",
    instituteName: "Institute of Engineering",
    departmentId: "dept-cse",
    departmentName: "Computer Science",
    industryId: "ind-1",
    industryName: "Infosys",
    thrustArea: "AI & Data Science",
    mouDate: "2025-01-10",
    durationMonths: 36,
    isActive: true,
    newCourses: 2,
    caseStudies: 4,
    partialDelivery: 3,
    academicActivities: 5,
    faculty: { trainings: 3, seminars: 2, workshops: 4, conferences: 1 },
    students: { trainings: 6, seminars: 3, workshops: 5, conferences: 1 },
    consultancyProjects: [
      { title: "Predictive Analytics Lab", amount: 900000 },
      { title: "AI Curriculum Advisory", amount: 350000 }
    ],
    researchGrants: [
      { title: "Responsible AI Toolkit", amount: 1200000, fundingAgency: "Infosys Foundation" }
    ],
    csrFund: 500000,
    centresOfExcellence: 1,
    innovationLabs: 1,
    studentProjects: 12,
    internships: 18,
    placements: 8
  },
  {
    id: "collab-002",
    universityId: "uni-1",
    universityName: "MIT University",
    campusId: "campus-blr",
    campusName: "Bengaluru Campus",
    instituteId: "inst-eng",
    instituteName: "Institute of Engineering",
    departmentId: "dept-ece",
    departmentName: "Electronics",
    industryId: "ind-2",
    industryName: "Bosch",
    thrustArea: "Embedded Systems",
    mouDate: "2024-08-15",
    durationMonths: 24,
    isActive: true,
    newCourses: 1,
    caseStudies: 3,
    partialDelivery: 2,
    academicActivities: 4,
    faculty: { trainings: 2, seminars: 1, workshops: 2, conferences: 1 },
    students: { trainings: 5, seminars: 2, workshops: 4, conferences: 1 },
    consultancyProjects: [{ title: "IoT Validation Setup", amount: 700000 }],
    researchGrants: [
      { title: "Automotive Sensor Network", amount: 1800000, fundingAgency: "Bosch R&D" }
    ],
    csrFund: 200000,
    centresOfExcellence: 0,
    innovationLabs: 1,
    studentProjects: 10,
    internships: 14,
    placements: 6
  },
  {
    id: "collab-003",
    universityId: "uni-1",
    universityName: "MIT University",
    campusId: "campus-pune",
    campusName: "Pune Campus",
    instituteId: "inst-mgmt",
    instituteName: "Institute of Management",
    departmentId: "dept-mba",
    departmentName: "MBA",
    industryId: "ind-3",
    industryName: "Tata Motors",
    thrustArea: "Operations & Supply Chain",
    mouDate: "2023-11-01",
    durationMonths: 18,
    isActive: false,
    newCourses: 1,
    caseStudies: 6,
    partialDelivery: 1,
    academicActivities: 3,
    faculty: { trainings: 1, seminars: 2, workshops: 1, conferences: 0 },
    students: { trainings: 2, seminars: 4, workshops: 1, conferences: 0 },
    consultancyProjects: [{ title: "Supply Chain Audit", amount: 450000 }],
    researchGrants: [],
    csrFund: 0,
    centresOfExcellence: 0,
    innovationLabs: 0,
    studentProjects: 7,
    internships: 9,
    placements: 5
  },
  {
    id: "collab-004",
    universityId: "uni-1",
    universityName: "MIT University",
    campusId: "campus-pune",
    campusName: "Pune Campus",
    instituteId: "inst-science",
    instituteName: "Institute of Applied Sciences",
    departmentId: "dept-biotech",
    departmentName: "Biotechnology",
    industryId: "ind-4",
    industryName: "Serum Institute",
    thrustArea: "Biotech & Healthcare",
    mouDate: "2025-06-05",
    durationMonths: 48,
    isActive: true,
    newCourses: 2,
    caseStudies: 2,
    partialDelivery: 2,
    academicActivities: 6,
    faculty: { trainings: 2, seminars: 3, workshops: 2, conferences: 2 },
    students: { trainings: 4, seminars: 5, workshops: 3, conferences: 1 },
    consultancyProjects: [{ title: "Quality Validation Advisory", amount: 820000 }],
    researchGrants: [
      { title: "Vaccine Bioprocess Study", amount: 2100000, fundingAgency: "DBT" }
    ],
    csrFund: 750000,
    centresOfExcellence: 1,
    innovationLabs: 1,
    studentProjects: 15,
    internships: 22,
    placements: 11
  }
];
